[project]
name = "builders"
authors = [
    { name = "Builders Team", email = "info@builders.com"}
]
description = "Civil Engineering LMS for the Gulf Region"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
